from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('care/', views.carePage, name='care'),
    path('login/', views.loginPage, name='login'),
    path('signup/', views.registerPage, name='register'),
    path('logout/', views.logoutPage, name='logout'),
    path('mydata/', views.myData, name='mydata'),
    path('account/', views.accountPage, name='account'),
    path('personal/', views.personalPage, name='personal'),
    path('medicalInfo/', views.medicalInfoPage, name='medicalInfo'),
    path('setting/', views.setting, name='setting'),
    path('passwordsecurityPage/', views.passwordsecurityPage, name='passwordsecurityPage'),
    path('changePassword/', views.changePassword, name='changePassword'),
    path('update_fullname/', views.update_fullname, name='update_fullname'),
    path('update_gender/', views.update_gender, name='update_gender'),
    path('update_dob/', views.update_dob, name='update_dob'),
    path('update_email/', views.update_email, name='update_email'),
    path('update_nationality/', views.update_nationality, name='update_nationality'),
    path('update_language/', views.update_language, name='update_language'),
    path('update_height/', views.update_height, name='update_height'),
    path('update_weight/', views.update_weight, name='update_weight'),
    path('change_language/', views.change_language, name='change_language'),
    path('findHospital/', views.findHospital, name='findHospital'),
    path('hospitalInfo/<str:pk>/', views.hospitalInfo, name='hospitalInfo'),
    path('diagnose/', views.diagnose, name='diagnose_start'),
    path('diagnose/<int:question_id>/', views.diagnose, name='diagnose'),
    path('conclusion-detail/<int:id_conclusion>/', views.conclusion_detail, name='conclusion-detail'),
    path('history/', views.history, name='history'),
    path('saved/', views.saved, name='saved'),
    path('add_to_favourites/<int:hospital_id>/', views.add_to_favourites, name='add_to_favourites'),
    path('remove_from_favourites/<int:hospital_id>/', views.remove_from_favourites, name='remove_from_favourites'),
    path('filter/', views.filter, name='filter'),
]
