# Generated by Django 4.2.7 on 2024-02-05 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_hospital_closing_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='closing_time',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='opening_time',
        ),
        migrations.AddField(
            model_name='hospital',
            name='working_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
