# Generated by Django 4.2.7 on 2024-02-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_hospital_closing_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='hospital_photos/'),
        ),
    ]
