# Generated by Django 4.2.7 on 2024-02-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_question_follow_up_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='likelihood_ratio',
            field=models.FloatField(blank=True, help_text='Likelihood ratio for this answer if applicable.', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_first_question',
            field=models.BooleanField(default=False, help_text='Choose to ask this question as the first question.'),
        ),
    ]
