# Generated by Django 4.2.7 on 2024-02-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_answer_likelihood_ratio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='odds_less_than_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answer',
            name='odds_more_than_1',
            field=models.BooleanField(default=False),
        ),
    ]
