# Generated by Django 4.2.7 on 2024-02-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_symptomchecksession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptomchecksession',
            name='odds_percentage',
            field=models.TextField(),
        ),
    ]
