# Generated by Django 4.2.7 on 2024-02-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_symptomchecksession_odds_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptomchecksession',
            name='id_conclusion',
            field=models.TextField(default=0),
        ),
    ]
