# Generated by Django 4.2.7 on 2024-02-27 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_symptomchecksession_id_conclusion'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='insurance_photos/'),
        ),
    ]
