# Generated by Django 4.2.7 on 2024-02-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_language_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='map',
            field=models.ImageField(blank=True, null=True, upload_to='map_photos/'),
        ),
        migrations.AlterField(
            model_name='language',
            name='photo',
            field=models.ImageField(default='language_photos/default.jpg', upload_to='language_photos/'),
        ),
    ]
