# Generated by Django 4.2.7 on 2024-02-27 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_hospital_map_alter_language_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='direct_billing',
            field=models.BooleanField(default=False),
        ),
    ]
