# Generated by Django 4.2.7 on 2024-02-29 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_favouritehospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='supported_insurance',
            field=models.ManyToManyField(blank=True, to='home.insurance'),
        ),
    ]
