# Generated by Django 4.2.7 on 2024-03-01 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_hospital_supported_insurance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='map',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='photo',
        ),
        migrations.AlterField(
            model_name='hospital',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='HospitalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='hospital_photos/')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.hospital')),
            ],
        ),
    ]
