# Generated by Django 4.2.7 on 2024-03-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_distanceinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
